CREATE TYPE "levels" AS ENUM (
  'beginner',
  'intermediate',
  'advanced'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "category_id" int NOT NULL,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "level" levels NOT NULL,
  "teacher" varchar NOT NULL
);

CREATE TABLE "course_video" (
  "int" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "title" text NOT NULL,
  "url" varchar NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

ALTER TABLE "courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

insert into users (
	name,
	email,
	"password",
	age 
)values(
	'Mateo',
	'miketry21@gmail.com',
	'root',
	20
)
insert into users (
	name,
	email,
	"password",
	age 
)values(
	'Manuela',
	'manuela@gmail.com',
	'1234',
	18
)

insert into categories (
	name
) values(
	'software'
)
insert into categories (
	name
) values(
	'lifestyle'
)


insert into courses (
	user_id,
	category_id,
	title,
	description,
	"level",
	teacher 
) values(
	1,
	1,
	'Programacion en js',
	'lorem ipsum',
	'beginner',
	'Mateo'
)
insert into courses (
	user_id,
	category_id,
	title,
	description,
	"level",
	teacher 
) values(
	2,
	2,
	'Habitos sanos',
	'lorem ipsum',
	'intermediate',
	'Manuela'
)

insert into course_video (
	course_id,
	title,
	url
) values (
	1,
	'Habitos sanos',
	'www.link.com'
)

insert into course_video (
	course_id,
	title,
	url
) values (
	2,
	'Habitos malos',
	'www.link2.com'
)
